baseurl: 'https://www.paritosh.dev'
languageCode: en-us
title: "Paritosh Baghel"
googleAnalytics: ""
disqusShortname: ""
preserveTaxonomyNames: true
footnotereturnlinkcontents: â†©
disableHugoGeneratorInject: true
pluralizeListTitles: false
pygmentsCodeFences: false
pygmentsUseClasses: false
minify: false
paginate: 9999
disableKinds:
  - section
  - categories
  - tags

permalinks:
  writing: /:year/:month/:day/:slug/

params:
  description: "Paritosh Blog"

frontmatter:
  author: "Paritosh Baghel"
  github: 'https://github.com/paritoshmmmec'
  og_image: 
  sitename: "Paritosh Blog"
  twitter: '@paritosh_pi'

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed
markup:
  goldmark:
    renderer:
      unsafe: true


